apiVersion: apps/v1
kind: Deployment
metadata:
  name: termix
  namespace: termix
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: termix
  template:
    metadata:
      labels:
        app: termix
    spec:
      containers:
        - name: termix
          image: ghcr.io/lukegus/termix:2.7.1
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GUACD_HOST
              value: "localhost"
            - name: GUACD_TUNNEL_HOST
              value: "termix"
            - name: GUACD_RECORDING_PATH
              value: "/termix-data/session_recordings/guacamole"
          volumeMounts:
            - name: data
              mountPath: /app/data
              
        - name: guacd
          image: guacamole/guacd:1.6.0
          volumeMounts:
            - name: data
              mountPath: /termix-data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: termix-data
