services:
  portainer:
    image: portainer/portainer-ce:2.27.1
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-network
    restart: unless-stopped

volumes:
  portainer-data: {}

networks:
  portainer-network:
    name: portainer-network