apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: postgres-password
          volumeMounts:
            - name: pgdata-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata-storage
          persistentVolumeClaim:
            claimName: pg-data