# PostgreSQL data. Giving it a moderate size.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi