services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.28.0
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /alxzfs/data/media/audiobooks:/audiobooks
      - /alxzfs/data/media/podcasts:/podcasts
      - /alxzfs/data/media/ebooks:/ebooks
      - audiobookshelf-config:/config
      - audiobookshelf-meta:/metadata
    environment:
      - TZ=Europe/Bucharest
    networks:
      - audiobookshelf-network
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=audiobookshelf

  backup:
    container_name: audiobookshelf-backup
    image: offen/docker-volume-backup:v2.43.3
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: 0 4 * * *
      BACKUP_RETENTION_DAYS: 30
      BACKUP_FILENAME: audiobookshelf-bkp-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_STOP_DURING_BACKUP_LABEL: audiobookshelf
    volumes:
      - audiobookshelf-config:/backup/config-backup:ro
      - audiobookshelf-meta:/backup/meta-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/dev-disk-by-uuid-8d0556c2-d1a1-444d-8a92-79190f30687b/ssd2/backups/nas/audiobookshelf:/archive
    networks:
      - audiobookshelf-network

volumes:
  audiobookshelf-config: {}
  audiobookshelf-meta: {}

networks:
  audiobookshelf-network:
    name: audiobookshelf-network