services:
  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    ports:
      - 9100:9100
    networks:
      - node-exporter-network
    restart: unless-stopped

networks:
  node-exporter-network:
    name: node-exporter-network