services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - jellyfin-data:/config
      - jellyfin-cache:/cache
      - /alxzfs/data/media:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - jellyfin-network
    restart: unless-stopped

volumes:
  jellyfin-data: {}
  jellyfin-cache: {}

networks:
  jellyfin-network:
    name: jellyfin-network