services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.8
    container_name: crowdsec
    restart: unless-stopped
    environment:
      - COLLECTIONS=crowdsecurity/nginx
    volumes:
      - /home/alex/docker/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /home/alex/docker/nginx-proxy/logs:/var/log/npm:ro
      - crowdsec-config:/etc/crowdsec
      - crowdsec-db:/var/lib/crowdsec/data
    networks:
      - crowdsec-network
    
  crowdsec-iptables-bouncer:
    image: ghcr.io/alexmihai1984/cs-iptables-bouncer:0.0.2
    container_name: cloudflare-bouncer
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - CS_API_URL=${CS_API_URL}
      - CS_API_KEY=${CS_API_KEY}
    depends_on:
      - crowdsec
    volumes:
      - /home/alex/docker/crowdsec/crowdsec-cloudflare-bouncer.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml

volumes:
  crowdsec-config: {}
  crowdsec-db: {}

networks:
  crowdsec-network:
    name: crowdsec-network