apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: npm-tcp
  namespace: npm-ingress
spec:
  entryPoints:
    - websecure
  tls:
    passthrough: true
  routes:
    - match: >
        HostSNI(`notes.alexmihai.rocks`) ||
        HostSNI(`napogro.com`) ||
        HostSNI(`portofoolio.com`) ||
        HostSNI(`quickypass.com`)
      services:
        - name: npm-external
          port: 443

    - match: >
        HostSNI(`alexmihai.rocks`) &&
        !HostSNI(`links.alexmihai.rocks`) &&
        !HostSNI(`todo.alexmihai.rocks`) &&
        !HostSNI(`*.k3s.alexmihai.rocks`)
      services:
        - name: npm-external
          port: 443
