services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:2.12.0'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - nginx-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - nginx-proxy-network
    labels:
      - docker-volume-backup.stop-during-backup=nginx-proxy

  backup:
    container_name: nginx-proxy-backup
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_CRON_EXPRESSION: 10 13 * * *
      BACKUP_RETENTION_DAYS: 30
      BACKUP_FILENAME: nginx-proxy-bkp-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: nginx-proxy-bkp-latest.tar.gz
      BACKUP_STOP_DURING_BACKUP_LABEL: nginx-proxy
    volumes:
      - nginx-data:/backup/nginx-data-backup:ro
      - letsencrypt-data:/backupletsencrypt-data-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/external/ssd2/backups/pi5server/nginx-proxy:/archive
      
volumes:
  nginx-data: {}
  letsencrypt-data: {}

networks:
  nginx-proxy-network:
    name: nginx-proxy-network
