services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:2.12.0'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - nginx-data:/data
      - letsencrypt-data:/etc/letsencrypt
    networks:
      - nginx-proxy-network
      
volumes:
  nginx-data: {}
  letsencrypt-data: {}

networks:
  nginx-proxy-network:
    name: nginx-proxy-network
