apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2-replicas
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
reclaimPolicy: Delete
volumeBindingMode: Immediate