apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-3-replicas
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
