global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.68.112:9100']
        labels:
          server: nas.local
      - targets: ['192.168.68.118:9100']
        labels:
          server: mediaserver.local
      - targets: ['192.168.68.106:9100']
        labels:
          server: pi5server.local
      - targets: ['192.168.68.108:9100']
        labels:
          server: pi5server2.local
      - targets: ['192.168.68.121:9100']
        labels:
          server: pi5server3.local
      - targets: ['192.168.68.115:9100']
        labels:
          server: think1.local
      - targets: ['192.168.68.116:9100']
        labels:
          server: think2.local
      - targets: ['192.168.68.114:9100']
        labels:
          server: think3.local
      - targets: ['192.168.68.128:9100']
        labels:
          server: hope1.local
      - targets: ['192.168.68.129:9100']
        labels:
          server: hope2.local
    relabel_configs:
      - source_labels: [server]
        target_label: instance

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.68.112:8081']
        labels:
          server: nas.local
      - targets: ['192.168.68.118:8081']
        labels:
          server: mediaserver.local
      - targets: ['192.168.68.106:8081']
        labels:
          server: pi5server.local
      - targets: ['192.168.68.108:8081']
        labels:
          server: pi5server2.local
      - targets: ['192.168.68.121:8081']
        labels:
          server: pi5server3.local
    relabel_configs:
      - source_labels: [server]
        target_label: instance
