services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - /home/alex/docker/monitoring/prometheus:/etc/prometheus
      - prometheus-storage:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
      - '--web.enable-admin-api'
    ports:
      - 9090:9090
    networks:
      - monitoring-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    ports:
      - 9100:9100
    networks:
      - monitoring-network
    restart: unless-stopped

volumes:
  grafana-storage: {}
  prometheus-storage: {}

networks:
  monitoring-network:
    name: monitoring-network