apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k3s-cert
  namespace: cert-manager
spec:
  secretName: wildcard-k3s-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
  dnsNames:
  - "*.k3s.alexmihai.rocks"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer