services:
  portainer:
    image: portainer/portainer-ce:2.33.2
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-network
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=portainer

volumes:
  portainer-data: {}

networks:
  portainer-network:
    name: portainer-network