apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: vikunja
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              value: "vikunja"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "vikunja"
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-data
---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: vikunja
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
