apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vikunja
          image: vikunja/vikunja
          ports:
            - containerPort: 3456
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "https://todo.alexmihai.rocks"
            - name: VIKUNJA_DATABASE_HOST
              value: "mariadb"
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: MYSQL_PASSWORD
            - name: VIKUNJA_DATABASE_TYPE
              value: "mysql"
            - name: VIKUNJA_DATABASE_USER
              value: "vikunja"
            - name: VIKUNJA_DATABASE_DATABASE
              value: "vikunja"
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secret
                  key: VIKUNJA_SERVICE_JWTSECRET
          volumeMounts:
            - name: vikunja-config
              mountPath: /app/vikunja/config.yml
              subPath: config.yml
            - name: vikunja-files
              mountPath: /app/vikunja/files
      volumes:
        - name: vikunja-config
          secret:
            secretName: vikunja-secret
        - name: vikunja-files
          persistentVolumeClaim:
            claimName: vikunja-files
---

apiVersion: v1
kind: Service
metadata:
  name: vikunja
  namespace: vikunja
spec:
  selector:
    app: vikunja
  ports:
    - port: 3456
      targetPort: 3456
  type: ClusterIP
