services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.1.1
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.alexmihai.rocks,pi5server2.local:5000,192.168.68.108:5000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000 # optional, your user id
      PGID: 1003 # optional, your group id
    ports:
      - 5000:3000
    volumes:
      - /home/alex/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped