services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.1.1
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.alexmihai.rocks,pi5server2.local:5000,192.168.68.108:5000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000 # optional, your user id
      PGID: 1003 # optional, your group id
    ports:
      - 5000:3000
    volumes:
      - /home/alex/docker/homepage:/app/config # Make sure your local config directory exists
      - /home/alex/docker/homepage/homepage-background.jpg:/app/public/images/homepage-background.jpg
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      - homepage-network
    labels:
      - docker-volume-backup.stop-during-backup=homepage
    
  backup:
    container_name: homepage-backup
    image: offen/docker-volume-backup:v2.43.3
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: 52 18 * * *
      BACKUP_RETENTION_DAYS: 30
      BACKUP_FILENAME: homepage-bkp-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: homepage-bkp-latest.tar.gz
      BACKUP_STOP_DURING_BACKUP_LABEL: homepage
    volumes:
      - /home/alex/docker/homepage:/backup/homepage:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/external/ssd2/backups/pi5server2/homepage:/archive
    networks:
      - homepage-network

networks:
  homepage-network:
    name: homepage-network