services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - /media/ssd2/minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - minio-network

networks:
  minio-network:
    name: minio-network