services:
  database:
    container_name: alexmihai-rocks-mariadb
    image: mariadb:11.5.2
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - alexmihai-rocks-network
    labels:
      - docker-volume-backup.stop-during-backup=alexmihai-rocks

  wordpress:
    container_name: alexmihai-rocks-wordpress
    depends_on:
      - database
    image: wordpress:6.6.2-apache
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://alexmihai.rocks');
        define('WP_SITEURL', 'https://alexmihai.rocks'); 
    volumes:
      - wp-html:/var/www/html
    networks:
      - alexmihai-rocks-network
      - nginx-proxy-network
    labels:
      - docker-volume-backup.stop-during-backup=alexmihai-rocks

  backup:
    container_name: alexmihai-rocks-backup
    image: offen/docker-volume-backup:v2.43.3
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: 0 5 * * *
      BACKUP_RETENTION_DAYS: 30
      BACKUP_FILENAME: alexmihai-rocks-bkp-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: alexmihai-rocks-bkp-latest.tar.gz
      BACKUP_STOP_DURING_BACKUP_LABEL: alexmihai-rocks
    volumes:
      - db-data:/backup/db-data-backup:ro
      - wp-html:/backup/wp-html-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/external/ssd2/backups/pi5server/alexmihai-rocks:/archive
    networks:
      - alexmihai-rocks-network

volumes:
  db-data: {}
  wp-html: {}

networks:
  nginx-proxy-network:
    name: nginx-proxy-network
    external: true
  alexmihai-rocks-network:
    name: alexmihai-rocks-network
  