services:
  database:
    container_name: alexmihai-rocks-mariadb
    image: mariadb:11.5.2
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - /var/docker/volumes/alexmihai-rocks/db-data:/var/lib/mysql
    networks:
      - alexmihai-rocks-network

  wordpress:
    container_name: alexmihai-rocks-wordpress
    depends_on:
      - database
    image: wordpress:6.6.2-apache
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://alexmihai.rocks');
        define('WP_SITEURL', 'https://alexmihai.rocks'); 
    volumes:
      - /var/docker/volumes/alexmihai-rocks/wp-html:/var/www/html
    networks:
      - alexmihai-rocks-network
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    name: nginx-proxy-network
    external: true
  alexmihai-rocks-network:
    name: alexmihai-rocks-network
  