services:
  influxdb:
    image: influxdb:2.2
    container_name: scrutiny-influxdb
    restart: unless-stopped
    ports:
      - 2086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-etc:/etc/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - scrutiny-network

  web:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny-web
    restart: unless-stopped
    ports:
      - 2080:8080
    volumes:
      - scrutiny-data:/opt/scrutiny/config
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    networks:
      - scrutiny-network

  collector:
    image: ghcr.io/analogj/scrutiny:master-collector
    container_name: scrutiny-collector
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - /run/udev:/run/udev:ro
    environment:
      COLLECTOR_API_ENDPOINT: 'http://web:8080'
      COLLECTOR_HOST_ID: 'nas'
      # If true forces the collector to run on startup (cron will be started after the collector completes)
      # see: https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#collector-trigger-on-startup
      COLLECTOR_RUN_STARTUP: true
      COLLECTOR_DEVICE_OPTIONS: "/dev/sda=-d ata"
    depends_on:
      web:
        condition: service_healthy
    devices:
      - /dev/disk/by-id/ata-KINGSTON_SUV500240G_50026B728217A87D:/dev/sda # SSD OS
      - /dev/disk/by-id/ata-ST6000VN0021-1ZA17Z_Z4D3DJYY:/dev/sdb # HDD sus
      - /dev/disk/by-id/ata-ST6000VN0021-1ZA17Z_Z4D3Q29A:/dev/sdc # HDD jos
    networks:
      - scrutiny-network

volumes:
  influxdb-data: {}
  influxdb-etc: {}
  scrutiny-data: {}

networks:
  scrutiny-network:
    name: scrutiny-network