apiVersion: v1
kind: Service
metadata:
  name: k3s-api
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-apiserver
  ports:
    - port: 6443
      targetPort: 6443
  type: LoadBalancer
  loadBalancerIP: 192.168.68.98
