services:
  ittools:
    image: 'ghcr.io/corentinth/it-tools:2024.10.22-7ca5933'
    container_name: it-tools
    ports:
        - '8101:80'
    restart: unless-stopped
    networks:
      - ittools-network

networks:
  ittools-network:
    name: ittools-network