services:
  collector:
    image: ghcr.io/analogj/scrutiny:master-collector
    container_name: scrutiny-collector
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - '/run/udev:/run/udev:ro'
    environment:
      COLLECTOR_API_ENDPOINT: 'http://192.168.68.118:2080'
      COLLECTOR_HOST_ID: 'mediaserver'
      # If true forces the collector to run on startup (cron will be started after the collector completes)
      # see: https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#collector-trigger-on-startup
      COLLECTOR_RUN_STARTUP: true
    devices:
      - "/dev/sda2"
      - "/dev/sdb2"
      - "/dev/sdc2"
    networks:
      - scrutiny-network

networks:
  scrutiny-network:
    name: scrutiny-network
