services:
  cloudflare-ddns:
    image: alexmihai1984/cloudflare-ddns:1.0.1
    container_name: cloudflare-ddns
    restart: unless-stopped

networks:
  cloudflare-ddns-network:
    name: cloudflare-ddns-network
