services:
  cloudflare-ddns:
    image: alexmihai1984/cloudflare-ddns:3.0.0
    container_name: cloudflare-ddns
    restart: unless-stopped
    networks:
      - cloudflare-ddns-network
    volumes:
      - /home/alex/docker/cloudflare-ddns/application.yml:/application.yml

networks:
  cloudflare-ddns-network:
    name: cloudflare-ddns-network
