services:
  cloudflare-ddns:
    image: alexmihai1984/cloudflare-ddns:2.1.1
    container_name: cloudflare-ddns
    restart: unless-stopped
    volumes:
      - /home/alex/docker/cloudflare-ddns/application.yml:/application.yml

networks:
  cloudflare-ddns-network:
    name: cloudflare-ddns-network
