services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:1.3.0
    restart: unless-stopped
    container_name: speedtest-tracker
    ports:
      - 8080:80
      - 8443:443
    environment:
      APP_KEY: ${APP_KEY}
      PUBLIC_DASHBOARD: ${PUBLIC_DASHBOARD}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: "0 */2 * * *"
      DISPLAY_TIMEZONE: Europe/Bucharest
      APP_URL: https://speedtest.alexmihai.rocks
      ASSET_URL: https://speedtest.alexmihai.rocks
    volumes:
      - speedtest-data:/config

volumes:
  speedtest-data: {}

networks:
  speedtest-network:
    name: speedtest-network